aws_region 		      = "us-east-1"
security_group_id   = "sg-xxxxxx"
enable_tcp          = "false"
enable_http         = "true"
enable_https        = "false"
enable_postgres     = "false"
enable_solr         = "false"
