variable "aws_region" {}
variable "sg_id_http" {}
variable "sg_id_https" {}
variable "sg_id_tcp" {}
variable "enable_tcp" {}
variable "enable_http" {}
variable "enable_https" {}
variable "enable_postgres" {}
variable "enable_solr" {}
