---
-
  name: "Install epel repo."
  yum:
    name: "{{ epel_repo_url }}"
    state: present
-
  name: "Import epel GPG key."
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
-
  name: "Install remi repo."
  yum:
    name: "{{ remi_repo_url }}"
    state: present
-
  name: "Import remi GPG key."
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present
-
  name: "Add remi-php72"
  yum_repository:
    description: "Remi's PHP 7.2 RPM repository"
    enabled: true
    gpgcheck: 1
    gpgkey: "{{ remi_repo_gpg_key_url }}"
    mirrorlist: "{{ remi_php_mirror_url }}"
    name: remi-php72
-
  package:
    name: "{{item}}"
    state: present
  name: "Install test dependencies"
  tags:
    - install_dependencies
  with_items: "{{ test_required_libs }}"
-
  name: "Install php7.2 on centos or derivates"
  tags:
    - install_php
  with_items:
    - php72
    - php72-php-fpm
    - php72-php-gd
    - php72-php-json
    - php72-php-mbstring
    - php72-php-mysqlnd
    - php72-php-xml
    - php72-php-xmlrpc
    - php72-php-opcache
  yum:
    name: "{{ item }}"
    state: latest
-
  lineinfile: "dest=\"{{ fastcgi_config_file }}\" regexp=\"{{ item.regex }}\" line=\"{{ item.line }}\""
  name: "edit php7.2-fpm user"
  tags:
    - set_php_fpm_nginx_user
  with_items:
    -
      line: "user = \"{{ nginx_user }}\""
      regex: "^user = .*"
    -
      line: "group = \"{{ nginx_user }}\""
      regex: "^group = .*"
    -
      line: "listen.owner = \"{{ nginx_user }}\""
      regex: "listen.owner.*"
    -
      line: "listen.group = \"{{ nginx_user }}\""
      regex: "listen.group.*"
    -
      line: "listen.mode = 0660"
      regex: "listen.mode.*"

-
  lineinfile: "dest=\"{{ php_ini_config_file }}\" regexp=\"{{ item.regex }}\" line=\"{{ item.line }}\""
  name: "edit php fpm ini file settings"
  tags:
    - edit_php_fpm_config_ini
  with_items:
    -
      line: "error_reporting = E_ALL"
      regex: "error_reporting = .*"
    -
      line: "display_errors = On"
      regex: "display_errors = .*"
    -
      line: cgi.fix_pathinfo=0
      regex: cgi.fix_pathinfo=.*
    -
      line: "memory_limit = 512M"
      regex: "memory_limit = .*"
    -
      line: "upload_max_filesize = 100M"
      regex: "upload_max_filesize = .*"
    -
      line: "date.timezone = UTC"
      regex: "date.timezone =.*"
-
  name: "Enable nginx repo."
  tags:
    - install_nginx
  template:
    dest: /etc/yum.repos.d/nginx.repo
    group: root
    mode: 420
    owner: root
    src: nginx.repo.j2
  when: true
-
  name: "Ensure nginx is installed."
  yum:
    name: nginx
    state: present
-
  changed_when: false
  command: getenforce
  ignore_errors: true
  name: "Check SELinux status"
  register: sestatus
  tags:
    - check_selinux_status
-
  ignore_errors: true
  name: "Allow SeLinux permission"
  shell: "setsebool -P httpd_can_network_connect 1"
  tags:
    - allow_selinux
  when: "\"Enabled\" in sestatus.stdout or \"Enforcing\" in sestatus.stdout"
-
  file:
    mode: 493
    path: "{{ nginx_root_dir }}/config"
    state: directory
  name: "create nginx configuration alternate directory"
  tags:
    - create_alternate_nginx_root
