#!/bin/bash
sudo yum update -y
sudo yum install python-setuptools python-pip -y
sudo pip install awscli
/usr/bin/aws s3 sync s3://devopslab-30180 /var/www/html/
/bin/touch /var/spool/cron/root
sudo /bin/echo '*/5 * * * * aws s3 sync s3://devopslab-30180 /var/www/html/' >> /var/spool/cron/root
